-- notice_market 테이블 생성

CREATE TABLE NOTICE_MARKET (
	NOTICE_NO NUMBER(5) primary key,
    notice_userId varchar2(30) not null,
    NOTICE_WRITER VARCHAR2(30) NOT NULL,
    NOTICE_TITLE VARCHAR2(200) NOT NULL,
    NOTICE_CONTENT VARCHAR2(1000) NOT NULL,
    NOTICE_HIT NUMBER(5) DEFAULT 0,
    NOTICE_DATE DATE,
    NOTICE_UPDATE DATE
);

INSERT INTO NOTICE_MARKET VALUES (1, 'id1', 'test_작성자1','test_제목1', 'test_내용1', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (2, 'id2', 'test_작성자2','test_제목2', 'test_내용2', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (3, 'id3', 'test_작성자3','test_제목3', 'test_내용3', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (4, 'id4', 'test_작성자4','test_제목4', 'test_내용4', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (5, 'id5', 'test_작성자5','test_제목5', 'test_내용5', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (6, 'id6', 'test_작성자6','test_제목6', 'test_내용6', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (7, 'id7', 'test_작성자7','test_제목7', 'test_내용7', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (8, 'id8', 'test_작성자8','test_제목8', 'test_내용8', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (9, 'id9', 'test_작성자9','test_제목9', 'test_내용9', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (10, 'id10', 'test_작성자10','test_제목10', 'test_내용10', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (11, 'id11', 'test_작성자11','test_제목11', 'test_내용11', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (12, 'id12', 'test_작성자12','test_제목12', 'test_내용12', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (13, 'id13', 'test_작성자13','test_제목13', 'test_내용13', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (14, 'id14', 'test_작성자14','test_제목14', 'test_내용14', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (15, 'id15', 'test_작성자15','test_제목15', 'test_내용15', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (16, 'id16', 'test_작성자16','test_제목16', 'test_내용16', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (17, 'id17', 'test_작성자17','test_제목17', 'test_내용17', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (18, 'id18', 'test_작성자18','test_제목18', 'test_내용18', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (19, 'id19', 'test_작성자19','test_제목19', 'test_내용19', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (20, 'id20', 'test_작성자20','test_제목20', 'test_내용20', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (21, 'id21', 'test_작성자21','test_제목21', 'test_내용21', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (22, 'id22', 'test_작성자22','test_제목22', 'test_내용22', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (23, 'id23', 'test_작성자23','test_제목23', 'test_내용23', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (24, 'id24', 'test_작성자24','test_제목24', 'test_내용24', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (25, 'id25', 'test_작성자25','test_제목25', 'test_내용25', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (26, 'id26', 'test_작성자26','test_제목26', 'test_내용26', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (27, 'id27', 'test_작성자27','test_제목27', 'test_내용27', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (28, 'id28', 'test_작성자28','test_제목28', 'test_내용28', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (29, 'id29', 'test_작성자29','test_제목29', 'test_내용29', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (30, 'id30', 'test_작성자30','test_제목30', 'test_내용30', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (31, 'id31', 'test_작성자31','test_제목31', 'test_내용31', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (32, 'id32', 'test_작성자32','test_제목32', 'test_내용32', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (33, 'id33', 'test_작성자33','test_제목33', 'test_내용33', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (34, 'id34', 'test_작성자34','test_제목34', 'test_내용34', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (35, 'id35', 'test_작성자35','test_제목35', 'test_내용35', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (36, 'id36', 'test_작성자36','test_제목36', 'test_내용36', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (37, 'id37', 'test_작성자37','test_제목37', 'test_내용37', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (38, 'id38', 'test_작성자38','test_제목38', 'test_내용38', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (39, 'id39', 'test_작성자39','test_제목39', 'test_내용39', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (41, 'id41', 'test_작성자41','test_제목41', 'test_내용41', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (42, 'id42', 'test_작성자42','test_제목42', 'test_내용42', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (43, 'id43', 'test_작성자43','test_제목43', 'test_내용43', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (44, 'id44', 'test_작성자44','test_제목44', 'test_내용44', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (45, 'id45', 'test_작성자45','test_제목45', 'test_내용45', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (46, 'id46', 'test_작성자46','test_제목46', 'test_내용46', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (47, 'id47', 'test_작성자47','test_제목47', 'test_내용47', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (48, 'id48', 'test_작성자48','test_제목48', 'test_내용48', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (49, 'id49', 'test_작성자49','test_제목49', 'test_내용49', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (50, 'id50', 'test_작성자50','test_제목50', 'test_내용50', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (51, 'id51', 'test_작성자51','test_제목51', 'test_내용51', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (52, 'id52', 'test_작성자52','test_제목52', 'test_내용52', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (53, 'id53', 'test_작성자53','test_제목53', 'test_내용53', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (54, 'id54', 'test_작성자54','test_제목54', 'test_내용54', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (55, 'id55', 'test_작성자55','test_제목55', 'test_내용55', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (56, 'id56', 'test_작성자56','test_제목56', 'test_내용56', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (57, 'id57', 'test_작성자57','test_제목57', 'test_내용57', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (58, 'id58', 'test_작성자58','test_제목58', 'test_내용58', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (59, 'id59', 'test_작성자59','test_제목59', 'test_내용59', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (60, 'id60', 'test_작성자60','test_제목60', 'test_내용60', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (61, 'id61', 'test_작성자61','test_제목61', 'test_내용61', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (62, 'id62', 'test_작성자62','test_제목62', 'test_내용62', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (63, 'id63', 'test_작성자63','test_제목63', 'test_내용63', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (64, 'id64', 'test_작성자64','test_제목64', 'test_내용64', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (65, 'id65', 'test_작성자65','test_제목65', 'test_내용65', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (66, 'id66', 'test_작성자66','test_제목66', 'test_내용66', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (67, 'id67', 'test_작성자67','test_제목67', 'test_내용67', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (68, 'id68', 'test_작성자68','test_제목68', 'test_내용68', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (69, 'id69', 'test_작성자69','test_제목69', 'test_내용69', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (70, 'id70', 'test_작성자70','test_제목70', 'test_내용70', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (71, 'id71', 'test_작성자71','test_제목71', 'test_내용71', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (72, 'id72', 'test_작성자72','test_제목72', 'test_내용72', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (73, 'id73', 'test_작성자73','test_제목73', 'test_내용73', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (74, 'id74', 'test_작성자74','test_제목74', 'test_내용74', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (75, 'id75', 'test_작성자75','test_제목75', 'test_내용75', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (76, 'id76', 'test_작성자76','test_제목76', 'test_내용76', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (77, 'id77', 'test_작성자77','test_제목77', 'test_내용77', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (78, 'id78', 'test_작성자78','test_제목78', 'test_내용78', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (79, 'id79', 'test_작성자79','test_제목79', 'test_내용79', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (80, 'id80', 'test_작성자80','test_제목80', 'test_내용80', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (81, 'id81', 'test_작성자81','test_제목81', 'test_내용81', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (82, 'id82', 'test_작성자82','test_제목82', 'test_내용82', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (83, 'id83', 'test_작성자83','test_제목83', 'test_내용83', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (84, 'id84', 'test_작성자84','test_제목84', 'test_내용84', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (85, 'id85', 'test_작성자85','test_제목85', 'test_내용85', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (86, 'id86', 'test_작성자86','test_제목86', 'test_내용86', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (87, 'id87', 'test_작성자87','test_제목87', 'test_내용87', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (88, 'id88', 'test_작성자88','test_제목88', 'test_내용88', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (89, 'id89', 'test_작성자89','test_제목89', 'test_내용89', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (90, 'id90', 'test_작성자90','test_제목90', 'test_내용90', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (91, 'id91', 'test_작성자91','test_제목91', 'test_내용91', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (92, 'id92', 'test_작성자92','test_제목92', 'test_내용92', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (93, 'id93', 'test_작성자93','test_제목93', 'test_내용93', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (94, 'id94', 'test_작성자94','test_제목94', 'test_내용94', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (95, 'id95', 'test_작성자95','test_제목95', 'test_내용95', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (96, 'id96', 'test_작성자96','test_제목96', 'test_내용96', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (97, 'id97', 'test_작성자97','test_제목97', 'test_내용97', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (98, 'id98', 'test_작성자98','test_제목98', 'test_내용98', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (99, 'id99', 'test_작성자99','test_제목99', 'test_내용99', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (100, 'id10', 'test_작성자100','test_제목100', 'test_내용100', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (101, 'id11', 'test_작성자101','test_제목101', 'test_내용101', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (102, 'id12', 'test_작성자102','test_제목102', 'test_내용102', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (103, 'id13', 'test_작성자103','test_제목103', 'test_내용103', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (104, 'id14', 'test_작성자104','test_제목104', 'test_내용104', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (105, 'id15', 'test_작성자105','test_제목105', 'test_내용105', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (106, 'id16', 'test_작성자106','test_제목106', 'test_내용106', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (107, 'id17', 'test_작성자107','test_제목107', 'test_내용107', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (108, 'id18', 'test_작성자108','test_제목108', 'test_내용108', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (109, 'id19', 'test_작성자109','test_제목109', 'test_내용109', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (110, 'id110', 'test_작성자110','test_제목110', 'test_내용110', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (111, 'id111', 'test_작성자111','test_제목111', 'test_내용111', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (112, 'id112', 'test_작성자112','test_제목112', 'test_내용112', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (113, 'id113', 'test_작성자113','test_제목113', 'test_내용113', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (114, 'id114', 'test_작성자114','test_제목114', 'test_내용114', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (115, 'id115', 'test_작성자115','test_제목115', 'test_내용115', DEFAULT, SYSDATE, NULL);
INSERT INTO NOTICE_MARKET VALUES (116, 'id끝', 'test_작성자_끝','test_제목_끝', 'test_내용_끝', DEFAULT, SYSDATE, NULL);